AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  CDK TS Boiler

  CDK Typescript Boilerplate

Parameters:
  EventBusName:
    Type: String
    Description: Name of the app event bus
    Default: boiler

Globals:
  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 30

Resources:
  StatusGet:
    Type: AWS::Serverless::Function
    Properties:
      Description: HTTP GET returns API status
      CodeUri: dist/handlers/status-get
      Handler: index.handler
      MemorySize: 128
      Timeout: 30
      Architectures:
        - x86_64
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref EventBusName

  JobsGet:
    Type: AWS::Serverless::Function
    Properties:
      Description: GET all Jobs
      CodeUri: dist/handlers/jobs-get
      Handler: index.handler
      MemorySize: 128
      Timeout: 30
      Architectures:
        - arm64
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref EventBusName

Outputs:
  StatusGetLambda:
    Description: example lambda
    Value: !Ref StatusGet
